#!/bin/bash

# Mandatory Options
#SBATCH --export=NONE
#SBATCH --open-mode=append

# Generated by the `slurmworkflow` R package
#SBATCH --partition=short
#SBATCH --account=p32153
#SBATCH --mail-type=FAIL,TIME_LIMIT
#SBATCH --mail-user=tom.wolff@northwestern.edu
#SBATCH --cpus-per-task=1
#SBATCH --time=04:00:00
#SBATCH --mem=5G
#SBATCH --array=0-39
#SBATCH --export=SWF__ARRAY_OFFSET=1

# see https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -e

SWF_ROOT="$1"
SWF_CUR="$2"
source "$SWF_ROOT/SWF/lib.sh"
make_env_vars "$SWF_ROOT"
make_env_cur_vars "$SWF_CUR"

source "$SWF__STEP_SCRIPT"
